name: KBOT-CICD

on:
  push:
    branches:
      - develop

env:
  TARGETARCH: amd64
  TARGETOS: linux
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.actor }}/kbot

jobs: 
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests
        run: make test

      - name: Docker login
        uses: docker/login-action@v3
        with:
          # username: ${{ secrets.DOCKERHUB_USERNAME }}
          # password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_DOCKER_TOKEN }}
      
      - name: Build & push
        env: 
          APP: ${{ env.REPOSITORY }}
        run: make image push
    
  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps: 

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=strenv(VERSION) | .image.arch=strenv(TARGETARCH) | .image.registry=strenv(REGISTRY) | .image.repository=strenv(REPOSITORY) | .image.os=strenv(TARGETOS)' helm/values.yaml
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "update version $VERSION"
        git push
